#!/bin/csh

#set verbose

#
mkdir -p ref
cat intro.tex ./inc/intro.tex > ref/all.tex
#foreach file (`ls -f inc/*.tex`)
# foreach file (`cat intro.tex | egrep '[\]input' | egrep -v '^%' | sed 's/[\]input{//g;s/}$//g'` )
#     cat ${file} >> ref/all.tex;
# end

cd ref
#cp ~/lars/SCRIPTS/lars_to_bib .
#cp ~/lars/SCRIPTS/lars_to_bib.awk .

if ( `whoami` == phil ) then
  cp ~/lars/svn/lars.txt .
else
  cp ~/lars/lars.txt .  
endif

# with codes
echo 'y' | ./lars_to_bib -f mol_simul_title -c yes -s yes lars.txt all.tex ../inc/paper.lrs >& /dev/null

cd ../

#
pdflatex intro.tex >& /dev/null
#

egrep '^\!' intro.log > err.log
if ( `cat err.log | wc -l` != 0 ) then
  echo COMPILATION ERRORS
  cat err.log  
  echo look in intro.log for more details...
  exit
endif
rm err.log >& /dev/null
#

pdflatex intro.tex >& /dev/null
#

rm intro.log
exit
